# Generated by Django 4.1.3 on 2022-12-14 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("funcionarios", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Item",
            new_name="Funcionarios",
        ),
    ]
