# Generated by Django 4.1.3 on 2022-12-14 03:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Alunos", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Aluno",
            fields=[
                ("id_Aluno", models.AutoField(primary_key=True, serialize=False)),
                ("nome_Aluno", models.CharField(max_length=100)),
                ("telefone", models.CharField(max_length=100)),
                ("sexo", models.CharField(max_length=100)),
                ("setor", models.CharField(max_length=11)),
                ("CPF", models.CharField(max_length=11)),
            ],
        ),
        migrations.DeleteModel(
            name="Alunos",
        ),
    ]
